# Generated by Django 5.1.6 on 2025-10-01 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_user_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="newsletter_subscribed",
            field=models.BooleanField(
                default=True, verbose_name="뉴스레터 구독 여부"
            ),
        ),
    ]
