"""Stats refresh queue 메시지 envelope 헬퍼.

Plan.md §3.3 — consumer 측 보강으로 외부 producer 변경 없이 구 envelope 을
신규 필드(`requestId`, `enqueuedAt`, `reclaimedCount`, `requestedBy`) 까지 확장.

사용 시점:
    - admin `update_stats` (F5) 에서 큐 푸시 전: build_envelope
    - consumer._process_message 의 BLMOVE 직후: ensure_envelope
"""

import uuid

from utils.utils import get_local_now


def build_envelope(
    user_id: int,
    requested_by: int | None = None,
    request_id: str | None = None,
) -> dict:
    """Producer 측에서 완전한 envelope 을 만들어 큐에 넣는 헬퍼."""
    now_iso = get_local_now().isoformat()
    return {
        "requestId": request_id or str(uuid.uuid4()),
        "userId": user_id,
        "requestedAt": now_iso,
        "requestedBy": requested_by,
        "retryCount": 0,
        "reclaimedCount": 0,
        "enqueuedAt": now_iso,
        "lastAttemptAt": None,
        "_autoGeneratedFields": [],
    }


def ensure_envelope(raw: dict) -> dict:
    """누락된 필드를 consumer 측에서 보강. 기존 필드는 절대 덮어쓰지 않음.

    `_autoGeneratedFields` 에 보강 흔적을 남겨 감사/디버깅 가능하게 함.
    """
    msg = dict(raw)  # shallow copy
    generated = []
    now_iso = get_local_now().isoformat()

    if "requestId" not in msg:
        msg["requestId"] = str(uuid.uuid4())
        generated.append("requestId")

    if "enqueuedAt" not in msg:
        # 가능하면 requestedAt, 없으면 현재 시각
        msg["enqueuedAt"] = msg.get("requestedAt", now_iso)
        generated.append("enqueuedAt")

    if "reclaimedCount" not in msg:
        msg["reclaimedCount"] = 0
        generated.append("reclaimedCount")

    if "requestedBy" not in msg:
        msg["requestedBy"] = None
        generated.append("requestedBy")

    if "retryCount" not in msg:
        msg["retryCount"] = 0
        generated.append("retryCount")

    # 기존 _autoGeneratedFields 가 있으면 합치고, 없으면 신규 생성
    if generated:
        existing = msg.get("_autoGeneratedFields") or []
        if not isinstance(existing, list):
            existing = []
        msg["_autoGeneratedFields"] = existing + generated

    return msg
