# Generated by Django 5.1.6 on 2025-03-13 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QRLoginToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정 일시"),
                ),
                (
                    "token",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="로그인용 QR 토큰"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        verbose_name="QR Code 만료 시간(기본값 5분 후)"
                    ),
                ),
                (
                    "is_used",
                    models.BooleanField(default=False, verbose_name="사용 여부"),
                ),
                (
                    "ip_address",
                    models.CharField(
                        blank=True,
                        max_length=45,
                        null=True,
                        verbose_name="요청한 IP 주소",
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="요청한 디바이스 정보",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="유저",
                    ),
                ),
            ],
            options={
                "verbose_name": "QR 로그인 토큰",
                "verbose_name_plural": "QR 로그인 토큰 목록",
                "indexes": [
                    models.Index(fields=["token"], name="qrcode_qrlo_token_8e6396_idx"),
                    models.Index(
                        fields=["expires_at"], name="qrcode_qrlo_expires_3bef58_idx"
                    ),
                ],
            },
        ),
    ]
