# Generated by Django 5.2.9 on 2026-04-17 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0014_user_newsletter_subscribed"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatsRefreshRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="생성 일시"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="수정 일시"
                    ),
                ),
                (
                    "request_id",
                    models.UUIDField(
                        db_index=True, unique=True, verbose_name="요청 ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "큐에 적재"),
                            ("PROCESSING", "처리 중"),
                            ("SUCCESS", "성공"),
                            ("FAILED", "실패 (재시도 중)"),
                            ("DLQ", "DLQ 이동 (재시도 포기)"),
                        ],
                        db_index=True,
                        default="QUEUED",
                        max_length=16,
                        verbose_name="상태",
                    ),
                ),
                (
                    "retry_count",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="retry 횟수"
                    ),
                ),
                (
                    "reclaimed_count",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="reclaim 횟수"
                    ),
                ),
                (
                    "last_error",
                    models.TextField(
                        blank=True, default="", verbose_name="마지막 에러"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="완료 일시"
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_stats_refreshes",
                        to="users.user",
                        verbose_name="요청자",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats_refresh_requests",
                        to="users.user",
                        verbose_name="대상 사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stats Refresh 요청",
                "verbose_name_plural": "Stats Refresh 요청 목록",
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="ops_trackin_status_059d86_idx",
                    )
                ],
            },
        ),
    ]
