# Generated by Django 5.2.9 on 2026-04-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ops_tracking", "0001_initial"),
        ("users", "0014_user_newsletter_subscribed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statsrefreshrequest",
            name="request_id",
            field=models.UUIDField(unique=True, verbose_name="요청 ID"),
        ),
        migrations.AlterField(
            model_name="statsrefreshrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("QUEUED", "큐에 적재"),
                    ("PROCESSING", "처리 중"),
                    ("SUCCESS", "성공"),
                    ("FAILED", "실패 (재시도 중)"),
                    ("DLQ", "DLQ 이동 (재시도 포기)"),
                ],
                default="QUEUED",
                max_length=16,
                verbose_name="상태",
            ),
        ),
        migrations.AddConstraint(
            model_name="statsrefreshrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["QUEUED", "PROCESSING"])),
                fields=("user",),
                name="uniq_inflight_per_user",
            ),
        ),
    ]
