# Generated by Django 5.2.9 on 2026-06-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insight", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="weeklytrend",
            name="review_status",
            field=models.CharField(
                choices=[
                    ("ready", "검수 불필요"),
                    ("needs_review", "검수 대기(발송 보류)"),
                    ("approved", "검수 승인"),
                ],
                default="ready",
                max_length=20,
                verbose_name="검수 상태",
            ),
        ),
    ]
