# Generated by Django 5.2.9 on 2026-06-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insight", "0002_weeklytrend_review_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="FilterLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="생성 일시"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="수정 일시"
                    ),
                ),
                (
                    "slug",
                    models.CharField(max_length=500, verbose_name="글 slug"),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("rejected", "검수에서 제거"),
                            ("approved", "검수 승인"),
                            ("escaped", "통과 후 스팸 판명"),
                        ],
                        max_length=20,
                        verbose_name="결정",
                    ),
                ),
                (
                    "score",
                    models.FloatField(default=0.0, verbose_name="필터 점수"),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True, default="", verbose_name="사유"
                    ),
                ),
                (
                    "decided_by",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="결정자",
                    ),
                ),
            ],
            options={
                "verbose_name": "광고 필터 라벨",
                "verbose_name_plural": "광고 필터 라벨 목록",
            },
        ),
    ]
